# =================================================================================================
# Here is global, all global key can't conflicts with other hotkeys
confirm = ['enter', 'l', "d"]
quit = ['esc']
# movement
list_up = ["w"]
list_down = ["s"]
# file panel control
close_file_panel = ['x', '']
create_new_file_panel = ['n', '']
next_file_panel = ['tab', 'L']
previous_file_panel = ['shift+left', 'H', "A"]
toggle_file_preview_panel = ['f', '']
# change focus
focus_on_process_bar = ['p', '']
focus_on_sidebar = ['b', '']
focus_on_metadata = ['m', '']
# create file/directory and rename 
file_panel_item_create = ['ctrl+n', '']
file_panel_item_rename = ['ctrl+r', '']
# file operate
copy_items = ['ctrl+c', '']
paste_items = ['ctrl+v', '']
cut_items = ['ctrl+x', '']
delete_items = ['ctrl+d', 'delete']
# compress and extract
extract_file = ['ctrl+e', '']
compress_file = ['ctrl+a', '']
# editor
open_file_with_editor = ['e', '']
open_current_directory_with_editor = ['E', '']
# else
pinned_directory = ['P', '']
toggle_dot_file = ['.', '']
change_panel_mode = ['v', '']
open_help_menu = ['?', '']
open_command_line = [':', '']
# =================================================================================================
# Here is typing hotkey can conflict with all hotkeys
confirm_typing = ['enter', '']
cancel_typing = ['ctrl+c', 'esc']
# =================================================================================================
# Here is normal mode hotkey you can conflicts with other mode (can't conflicts with global hotkey)
parent_directory = ["a", 'h', 'backspace']
search_bar = ['/', 'q']
# =================================================================================================
# Here is select mode hotkey you can conflicts with other mode (can't conflicts with global hotkey)
file_panel_select_mode_items_select_down = ['shift+down', 'J']
file_panel_select_mode_items_select_up = ['shift+up', 'K']
file_panel_select_all_items = ['ctrl+a', '']
